PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE usuarios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  nombre TEXT NOT NULL,
  password_hash TEXT,
  es_invitado BOOLEAN DEFAULT 0,
  fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
  es_admin BOOLEAN DEFAULT 0
);
INSERT INTO "usuarios" ("id","email","nombre","password_hash","es_invitado","fecha_creacion","es_admin") VALUES(1,'julianayazmin2@gmail.com','juliana','0ffe1abd1a08215353c233d6e009613e95eec4253832a761af28ff37ac5a150c',0,'2026-09-09 22:09:08',0);
INSERT INTO "usuarios" ("id","email","nombre","password_hash","es_invitado","fecha_creacion","es_admin") VALUES(2,'fgpereyra.92@gmail.com','fede',NULL,1,'2026-09-09 22:16:10',0);
INSERT INTO "usuarios" ("id","email","nombre","password_hash","es_invitado","fecha_creacion","es_admin") VALUES(3,'ejemplo@ej','Diego Maldonado',NULL,1,'2026-09-10 10:09:36',0);
INSERT INTO "usuarios" ("id","email","nombre","password_hash","es_invitado","fecha_creacion","es_admin") VALUES(4,'prueba@gmail.com','probando',NULL,1,'2026-09-11 01:31:45',0);
INSERT INTO "usuarios" ("id","email","nombre","password_hash","es_invitado","fecha_creacion","es_admin") VALUES(5,'probando.2@jotmail','probador 22',NULL,1,'2026-09-11 01:35:58',0);
INSERT INTO "usuarios" ("id","email","nombre","password_hash","es_invitado","fecha_creacion","es_admin") VALUES(6,'admin@example.com','Jjj',NULL,1,'2026-09-11 01:46:20',0);
INSERT INTO "usuarios" ("id","email","nombre","password_hash","es_invitado","fecha_creacion","es_admin") VALUES(7,'admin@cotaber','probando',NULL,1,'2026-09-11 02:05:20',0);
INSERT INTO "usuarios" ("id","email","nombre","password_hash","es_invitado","fecha_creacion","es_admin") VALUES(8,'cotizadoraberturas@gmail.com','Administrador','c77d7c85e7bd0c20d2d28e69cdceded2833fcaed088f1a4e22f73ab57258abec',0,'2026-09-11 02:19:00',0);
INSERT INTO "usuarios" ("id","email","nombre","password_hash","es_invitado","fecha_creacion","es_admin") VALUES(9,'anonimo@foro.invalid','Anónimo',NULL,1,'2026-09-14 11:54:58',0);
CREATE TABLE categorias (
  id TEXT PRIMARY KEY,
  nombre TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  descripcion TEXT
);
INSERT INTO "categorias" ("id","nombre","slug","descripcion") VALUES('cotizador','Cotizador de aberturas','cotizador','Preguntas sobre el Cotizador de Aberturas');
INSERT INTO "categorias" ("id","nombre","slug","descripcion") VALUES('calculos','Calculos, formulas, descuentos','calculos','Dudas sobre fórmulas y descuentos');
INSERT INTO "categorias" ("id","nombre","slug","descripcion") VALUES('consultas','Consultas generales','consultas','Preguntas generales sobre el programa');
INSERT INTO "categorias" ("id","nombre","slug","descripcion") VALUES('sistemas','Sistemas','sistemas','Preguntas sobre sistemas operativos y requisitos');
INSERT INTO "categorias" ("id","nombre","slug","descripcion") VALUES('sugerencias','Sugerencias','sugerencias','Propuestas de mejora para el programa');
INSERT INTO "categorias" ("id","nombre","slug","descripcion") VALUES('offtopic','Off topic','offtopic','Temas fuera del alcance del programa');
CREATE TABLE preguntas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  usuario_id INTEGER NOT NULL,
  categoria_id TEXT,
  titulo TEXT NOT NULL,
  contenido TEXT NOT NULL,
  imagenes TEXT,
  fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
  votos INTEGER DEFAULT 0,
  FOREIGN KEY(usuario_id) REFERENCES usuarios(id),
  FOREIGN KEY(categoria_id) REFERENCES categorias(id)
);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(3,9,'consultas','¿Las actualizaciones borran mis presupuestos?','Cuando salga una versión nueva, ¿pierdo mis presupuestos, precios o fórmulas?',NULL,'2026-09-14 11:57:24',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(4,9,'consultas','Cómo activo la licencia y qué pasa si cambio de PC','¿Cómo activo la licencia? ¿Y si cambio de computadora?',NULL,'2026-09-14 11:57:26',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(5,9,'consultas','La prueba gratis y la leyenda VERSIÓN DE PRUEBA','Bajé el programa. ¿Cuánto dura la prueba y por qué los PDF salen con la leyenda VERSIÓN DE PRUEBA?',NULL,'2026-09-14 11:57:28',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(6,9,'sistemas','Windows muestra un aviso de seguridad al abrir el programa','Al abrir el programa, Windows me dice que protegió mi PC. ¿Es un virus?',NULL,'2026-09-14 11:57:30',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(7,9,'sistemas','Qué computadora necesito','¿Qué requisitos tiene que tener mi PC para usar el programa?',NULL,'2026-09-14 11:57:32',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(8,9,'cotizador','Elegir rodamiento o cierre según la abertura','Según el peso de la hoja uso rodamiento simple o doble, y según la abertura cambia el cierre. ¿Tengo que armar un kit para cada caso?',NULL,'2026-09-14 11:57:34',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(9,9,'cotizador','¿El programa optimiza el corte de vidrio en planchas?','¿El programa me dice cómo cortar los paños de vidrio de las planchas?',NULL,'2026-09-14 11:57:36',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(10,9,'cotizador','Cómo cargo el stock y cuándo se descuenta','Quiero llevar el stock del depósito. ¿Cómo lo cargo y en qué momento se descuenta el material?',NULL,'2026-09-14 11:57:38',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(11,9,'calculos','El costo del aluminio me da cero','Cargo una abertura y el costo del aluminio da cero. ¿Qué falta?',NULL,'2026-09-14 11:57:40',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(12,9,'cotizador','Cómo cargo un pedido de presupuesto paso a paso','Me llegó un pedido con varias aberturas de distintas medidas y vidrios. ¿Cómo lo cargo?',NULL,'2026-09-14 11:57:42',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(13,9,'cotizador','Cómo importo desde Excel los perfiles de otra línea','Trabajo una línea que no viene cargada. ¿Cómo importo sus perfiles desde el Excel del fabricante?',NULL,'2026-09-14 11:57:44',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(14,9,'cotizador','Ventana corrediza con paño fijo abajo','Me pidieron una ventana corrediza con un paño fijo abajo. ¿Cómo la cargo?',NULL,'2026-09-14 11:57:46',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(15,9,'calculos','El contramarco y el tapajuntas, ¿se cargan como perfiles y se cuentan?','¿El tapajuntas o el contramarco los agrego a la lista de perfiles? ¿Después se cuentan en el presupuesto?',NULL,'2026-09-14 11:57:48',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(16,9,'cotizador','¿Se puede ocultar en el presupuesto cuánto aluminio y vidrio lleva cada abertura?','En el PDF que le mando al cliente aparece el aluminio y el vidrio que lleva cada abertura. ¿Se puede sacar?',NULL,'2026-09-14 11:57:50',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(17,9,'calculos','¿Hay que duplicar los m² del DVH porque la vidriería cobra las dos caras?','La vidriería me cobra las dos caras del DVH. ¿Tengo que duplicar los metros cuadrados que calcula el programa?',NULL,'2026-09-14 11:57:52',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(18,9,'calculos','El peso de la ventana da miles de kilos','En una ventana de 1 x 1 la columna de peso me marca 6.960 kg. ¿Por qué?',NULL,'2026-09-14 11:57:54',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(19,9,'calculos','El vidrio me da menos m² de lo esperado o los paños salen acostados','Cotizo una corrediza de 2 hojas de 1000 x 1000. El vidrio me da 0,71 m² con paños de 828 x 427, y me dijeron que tendría que dar unos 5 metros. ¿Qué está mal?',NULL,'2026-09-14 11:57:56',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(20,9,'cotizador','¿Los cortes los calcula el programa o los hago a mano?','Una vez cargada la ventana, ¿el programa me da la lista de cortes o la tengo que hacer aparte?',NULL,'2026-09-14 11:57:58',0);
INSERT INTO "preguntas" ("id","usuario_id","categoria_id","titulo","contenido","imagenes","fecha","votos") VALUES(21,9,'calculos','Cómo cargo los descuentos de cada perfil','Estoy armando una ventana en Módena. ¿Dónde pongo los descuentos de cada perfil, por ejemplo del 6200 y el 6201?',NULL,'2026-09-14 11:58:00',0);
CREATE TABLE respuestas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  usuario_id INTEGER NOT NULL,
  id_pregunta INTEGER NOT NULL,
  contenido TEXT NOT NULL,
  imagenes TEXT,
  fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
  votos INTEGER DEFAULT 0,
  FOREIGN KEY(usuario_id) REFERENCES usuarios(id),
  FOREIGN KEY(id_pregunta) REFERENCES preguntas(id)
);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(5,8,3,replace('No. En Ajustes, sección Versión y actualizaciones, usás Instalar actualización con el .zip de la versión nueva. El programa hace una copia de seguridad, reemplaza sólo el programa y deja intactos tus presupuestos, listas de precios y configuración.\n\nIgual conviene guardar una copia antes de cualquier cambio grande, con Crear copia de seguridad en Datos y respaldos. Si algo sale mal, Restaurar desde una copia vuelve a un respaldo anterior.','\n',char(10)),NULL,'2026-09-14 12:02:15',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(6,8,4,replace('La licencia es por equipo.\n1. Copiá el código de equipo que muestra la ventana de activación. También está en Ajustes, sección Licencia.\n2. Mandalo a cotizadoraberturas@gmail.com.\n3. Te llega una clave que empieza con COTIZ-. Pegala completa y el programa se activa.\n\nLa clave sirve sólo para esa computadora. Si cambiás de PC, instalá el programa en la nueva y pedí una clave con el código de la máquina nueva. Después copiá la carpeta de datos de la vieja, que abrís desde Ajustes, Datos y respaldos, Abrir carpeta de datos.\n\nSi el programa dice que la fecha del equipo está atrasada, corregí la fecha y hora de Windows y activá Establecer la hora automáticamente.','\n',char(10)),'["https://netunlock.github.io/cotizador-aberturas/img/foro/activacion.jpg"]','2026-09-14 12:02:17',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(7,8,5,replace('La prueba dura tres días y arranca sola la primera vez que abrís el programa, sin registrarte. Abajo a la izquierda ves cuántos días te quedan.\n\nDurante la prueba, todo lo que imprimís o exportás sale cruzado con la leyenda VERSIÓN DE PRUEBA. Vale para presupuestos, diagramas de corte, etiquetas, listas de materiales, órdenes de trabajo y el Excel. Es a propósito: la prueba es para que midas, cargues tus precios y veas si te sirve.\n\nCuando ponés la clave, la marca desaparece sin cerrar el programa. Los presupuestos que hiciste quedan guardados y los volvés a generar limpios. Para seguir usándolo, escribí a cotizadoraberturas@gmail.com con el código de equipo que muestra el programa.','\n',char(10)),'["https://netunlock.github.io/cotizador-aberturas/img/foro/prueba_marca.jpg"]','2026-09-14 12:02:18',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(8,8,6,replace('No. Pasa porque el programa no tiene una firma digital comercial. Hacé clic en Más información y después en Ejecutar de todas formas.\n\nDos consejos de instalación. Descomprimí el zip en una carpeta tuya, como Documentos o el Escritorio, y no en Archivos de programa, porque ahí Windows no deja actualizarlo. Y no saques el .exe de su carpeta, porque necesita los archivos que tiene al lado. Si lo querés a mano, creá un acceso directo.','\n',char(10)),NULL,'2026-09-14 12:02:19',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(9,8,7,replace('Funciona en cualquier PC de oficina razonablemente moderna, sin instalar nada más.\n- Windows 10 u 11 de 64 bits. No funciona en Windows 7 ni 8, ni en versiones de 32 bits.\n- 2 GB de memoria como mínimo, 4 GB recomendado.\n- 150 MB libres en disco, mejor 500 MB para presupuestos y respaldos.\n- Pantalla de 1024 x 600 como mínimo, recomendado 1366 x 768.\n- No necesita internet para trabajar, sólo para recibir la clave de activación.\n- No hace falta ser administrador.\n\nSi la letra te queda chica, agrandá la interfaz en Ajustes, sección Apariencia, Tamaño de la interfaz.','\n',char(10)),NULL,'2026-09-14 12:02:21',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(10,8,8,replace('No hace falta. Se resuelve con una opción de la tipología de tipo accesorio.\n1. En Materiales y Costos, pestaña Tipologías, en Opciones de la tipología, declarás una opción de tipo accesorio. En el campo Opciones ponés los códigos que se pueden elegir, separados por coma.\n2. En Kits de accesorios elegís el kit y el renglón del rodamiento. En Lo elige la opción ponés la clave de la opción que declaraste.\n3. Al cargar la abertura aparece la lista, y el kit cobra y descuenta el accesorio elegido.\n\nEl accesorio que estaba en ese renglón del kit queda como valor por defecto.','\n',char(10)),NULL,'2026-09-14 12:02:22',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(11,8,9,replace('Sí. En Papeles de taller, el PDF de Corte acomoda los paños de todo el presupuesto dentro de las planchas. Las dibuja a escala, con la medida y la posición de cada paño.\n- Los paños van en franjas, porque el vidrio se corta de lado a lado. Así el plan se puede cortar en la mesa.\n- Los que dicen 90° se cortan girados.\n- Para cada tipo de vidrio dice cuántas planchas hacen falta y qué porcentaje se aprovecha.\n- Cada tipo de vidrio va por separado.\n\nLa medida de la plancha se carga en Materiales y Costos, pestaña Vidrios, en Plancha base. Si un paño no entra ni girado, el PDF lo lista aparte para pedirlo en medida especial.','\n',char(10)),'["https://netunlock.github.io/cotizador-aberturas/img/foro/corte_vidrio.jpg"]','2026-09-14 12:02:23',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(12,8,10,replace('El inventario viene desactivado. En la pantalla Inventario tocá Activar ahora.\n1. Con Alta de artículo elegís si es perfil, vidrio o accesorio, buscás el código y ponés la cantidad que tenés hoy. Sólo se incorpora lo que de verdad hay en depósito, no el catálogo entero.\n2. Los perfiles se cuentan en barras enteras, el vidrio en m² y los accesorios en su propia unidad. Si tenés 12 barras de un perfil, cargás 12 y no 72 metros.\n3. El saldo no se edita a mano. Usá Ingreso cuando llega material, Egreso cuando sale por fuera de una orden y Recuento cuando contaste el depósito y no coincide. Con Mínimo fijás el punto de reposición.\n\nEl material se descuenta al emitir la orden de trabajo, no al aprobar el presupuesto. Un presupuesto aprobado todavía no consumió nada. Lo que saca material del depósito es mandar a fabricar. Al emitir la orden, el programa te muestra antes lo que falta, artículo por artículo.','\n',char(10)),NULL,'2026-09-14 12:02:25',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(13,8,11,replace('Si recién bajaste el programa, lo más probable es que falten los precios. Los catálogos vienen con todo en $0, y el precio del kilo se carga por color en Materiales y Costos, pestaña Líneas y precios. Lo mismo pasa con el m² de cada vidrio y el precio de cada accesorio.\n\nSi los precios están cargados, falta una de dos cosas. O esa tipología no tiene fórmulas de despiece para la línea elegida, o los perfiles no tienen cargado el peso por metro.\n\nEl contador de advertencias, al lado del título de la lista de aberturas, te dice cuál es. Tocalo y cada aviso trae un botón que te lleva a la pantalla donde se corrige.','\n',char(10)),NULL,'2026-09-14 12:02:26',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(14,8,12,replace('Todo se hace en la pantalla Cotización.\n1. Completá el encabezado: número, fecha, días de validez y estado. El número se completa solo.\n2. Cargá los datos del cliente: razón social, CUIT o DNI, contacto, obra, localidad y forma de pago.\n3. Por cada posición del pedido tocá Agregar abertura. Elegí tipología, línea, color y vidrio. Cargá ancho y alto en milímetros, hojas y cantidad. A la derecha ves el costo en vivo.\n4. Lo que pide el cliente y no tiene un campo, como un cierre especial o un panel ciego, va en Observaciones de este ítem.\n5. Completá mano de obra y logística. El programa puede estimar las horas según los m² de cada abertura.\n6. Ajustá margen, descuento e IVA en el resumen.\n7. Guardá y generá el PDF.\n\nAntes de aceptar cada abertura podés tocar Ver despiece para revisar cortes, vidrio y accesorios.','\n',char(10)),NULL,'2026-09-14 12:02:27',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(15,8,13,replace('1. En Materiales y Costos, pestaña Líneas y precios, creá la línea.\n2. En la pestaña Perfiles elegí esa línea arriba. La importación va a la línea que tengas elegida, así que fijate antes de seguir.\n3. Tocá Importar catálogo y elegí el Excel. No hace falta prepararlo.\n4. Antes de guardar, el programa te muestra qué columnas reconoció, cuántos perfiles va a cargar y cuáles descarta y por qué.\n5. Aceptás. Los códigos que ya existían se actualizan, los nuevos se agregan y no se borra ninguno.\n\nEl Excel necesita como mínimo una columna de código y una de peso por metro. Si falta el largo de barra, toma 6 metros. No importa que los títulos no estén en la primera fila ni que arriba haya logo o notas. Si no reconoce una columna, renombrá el título a Código, Peso Kg/m o Largo de barra y volvé a importar.\n\nImportar trae los perfiles, pero todavía no despieza esa línea. Para cotizarla con cortes reales hay que cargar las fórmulas de despiece de cada tipología. Mientras tanto podés poner la línea en modo de costeo m2 y cotizarla por metro cuadrado.','\n',char(10)),'["https://netunlock.github.io/cotizador-aberturas/img/galeria-04-perfiles-aluminio.jpg"]','2026-09-14 12:02:29',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(16,8,14,replace('Hay dos formas.\n\nSi es por única vez, cargala como dos aberturas, la corrediza y un paño fijo, cada una con su medida. En las observaciones aclarás que van acopladas y sumás el perfil de acople. Cotizadas por separado, cada una lleva su marco completo y sobra un poco de aluminio. Para el presupuesto queda del lado seguro, pero no para el corte en el taller.\n\nSi la vas a hacer seguido, armala como tipología compuesta. En Materiales y Costos, pestaña Tipologías, creás la tipología y en el panel de paños cargás de qué está hecha:\n\nPaño 1: paño fijo, ancho A, alto ALTO_FIJO\nPaño 2: corrediza, ancho A, alto H - ALTO_FIJO - 45\n\nEl 45 es un ejemplo: ahí va el descuento del acople de tu línea. ALTO_FIJO se declara en Opciones de la tipología como opción de tipo número. Así, en cada abertura escribís cuánto mide el paño fijo de esa obra, sin crear una tipología por cada medida. El marco perimetral y el perfil de acople van en las fórmulas de despiece de la compuesta, como en cualquier tipología.\n\nEl dibujo del PDF es uno de los esquemas fijos del programa: corrediza, fijo, batiente, banderola o puerta batiente. Elegís el que corresponda en Dibujo en el PDF.','\n',char(10)),'["https://netunlock.github.io/cotizador-aberturas/img/galeria-03-pano-fijo.jpg"]','2026-09-14 12:02:30',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(17,8,15,replace('Sí. Una vez cargados entran en el peso, el costo, el listado de corte y las barras a comprar. Son dos pasos:\n1. El perfil, en Materiales y Costos, pestaña Perfiles, con su peso por metro y su largo de barra.\n2. Un renglón por pieza en Fórmulas de despiece, en cada tipología que lo lleve.\n\nEl contramarco suma en vez de restar, porque va por fuera del marco y mide más que el hueco. Por eso la fórmula es del tipo H + 53 y no H - 53.\n\nEn la columna Función poné OTRO para el contramarco y PREMARCO para el premarco. Nunca HOJA_HORIZONTAL ni HOJA_VERTICAL, porque esas dos le dicen al vidrio cuánto mide la hoja.\n\nEn la línea Actual de MDT, el premarco MT-0205 y el contramarco MT-0206 ya vienen en las fórmulas y se cortan siempre. Tené en cuenta dos cosas:\n- No tildes Incluye premarco en esas aberturas. Ese tilde suma aparte un costo de premarco por m², y lo estarías cobrando dos veces.\n- Si una obra no lleva premarco, lo más prolijo es una opción de la tipología. En Opciones de la tipología declarás una opción de tipo bool con la clave PREMARCO, y en los renglones del premarco ponés estas dos fórmulas:\n\nLargo: si(PREMARCO, H + 36, 0)\nCantidad: si(PREMARCO, 2, 0)\n\nAl cargar cada abertura tildás si lleva premarco o no. La otra salida es duplicar la tipología y dejar esos renglones en cantidad 0 en la copia.','\n',char(10)),NULL,'2026-09-14 12:02:31',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(18,8,16,replace('En la versión actual ese dato viene oculto en el PDF. Es información de taller, y al cliente final le da justo lo que necesita para pedir el mismo trabajo en otro lado.\n\nSi lo querés mostrar, andá a Materiales y Costos, pestaña Costos operativos, y poné el parámetro mostrar_consumo_pdf en 1. Con 0 queda oculto.','\n',char(10)),'["https://netunlock.github.io/cotizador-aberturas/img/foro/presupuesto.jpg"]','2026-09-14 12:02:32',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(19,8,17,replace('No. El programa muestra la superficie del paño una sola vez, que es la medida del vidrio que entra en la hoja. Las dos caras se contemplan en el precio, no en los metros.\n\nEl precio por m² que cargás en Vidrios tiene que ser el del DVH armado. Si tu vidriería no lo lista armado, sumá el precio de la primera cara, el de la segunda y el de la cámara. Ese total es el precio por m² del DVH. Si además duplicás los m², terminás cobrando cuatro caras.\n\nPara quedarte tranquilo, pedile a la vidriería el precio de los paños que te da el programa y comparalo con el costo de vidrio de esa abertura. Si te cotizan el doble, el precio que cargaste era de una sola cara. Se corrige en la ficha del vidrio, no en los metros.\n\nUn detalle: las vidrierías suelen cobrar un mínimo por paño y redondear para arriba. En paños chicos, como una banderola de baño, la factura real va a dar más que el cálculo. Para esos casos cargá un vidrio aparte con un precio por m² más alto, o subile el desperdicio.','\n',char(10)),NULL,'2026-09-14 12:02:34',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(20,8,18,replace('Una ventana de aluminio de 1 m² pesa entre 6 y 10 kilos. Si da miles, el peso de los perfiles está cargado en gramos por metro en lugar de kilos por metro.\n\nEs lo primero que hay que corregir. En el modo de costeo por kg, el costo del aluminio sale del peso, así que con el peso multiplicado por mil el aluminio sale mil veces más caro.\n\nRevisalo en Materiales y Costos, pestaña Perfiles, eligiendo la línea. El peso tiene que verse como 0,705 o 1,266, no como 705 o 1266.\n\nSi importás el catálogo desde Excel y el título de la columna dice g/m o grs/m, el programa convierte solo a kilos. Si la columna dice solamente Peso y los valores están en gramos, el programa descarta esos renglones y te avisa, porque ningún perfil pesa más de 20 kg por metro. En ese caso dividí por 1000 en el Excel y volvé a importar. Los códigos que ya existen se actualizan y no se duplica nada.','\n',char(10)),NULL,'2026-09-14 12:02:35',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(21,8,19,replace('Son dos cosas distintas.\n\nLos paños están acostados. En una corrediza de 2 hojas cada paño tiene que ser angosto y alto, y acá salen anchos y bajos. Con las fórmulas de Aluar para Módena, esa ventana da paños de 491 x 889 y 0,87 m².\n\nLa causa casi siempre está en la columna Función de las fórmulas de despiece. Esa columna no es una etiqueta. Le dice al programa cuánto mide la hoja:\n- HOJA_HORIZONTAL define el ancho de hoja, que en las fórmulas de vidrio se llama AH.\n- HOJA_VERTICAL define el alto de hoja, que se llama HH.\n\nLa pieza que se calcula con el ancho, como el zócalo con A/2 - 24, va con HOJA_HORIZONTAL. La que se calcula con el alto, como el parante con H - 79, va con HOJA_VERTICAL. Si están cruzadas, el vidrio sale cruzado.\n\nEl mismo error puede aparecer de otra forma. Si ninguna pieza está marcada como HOJA_HORIZONTAL, el programa no conoce el ancho de hoja y el vidrio puede salir más grande que la ventana entera. Suele pasar cuando una pieza de hoja quedó como MARCO_HORIZONTAL. La regla es simple: si la pieza es de hoja, su función empieza con HOJA.\n\nLos 5 metros no pueden ser metros cuadrados, porque la ventana entera mide 1 m². Son metros lineales, el perímetro de los paños, que sirve para contravidrio y burlete.\n\nPara comprobarlo, en Fórmulas de despiece tocá Probar despiece con la medida de la ventana. Ahí ves la medida de hoja y el paño de vidrio sin tocar ningún presupuesto. Si la tipología no tiene fórmula de vidrio propia, cargala con el botón Fórmulas de vidrio.','\n',char(10)),NULL,'2026-09-14 12:02:36',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(22,8,20,replace('Los calcula el programa. Con Ver despiece tenés cada corte con el código de perfil, el largo en milímetros, la cantidad de piezas y el peso. Se abre desde la lista de aberturas o antes de aceptar la abertura.\n\nPara el taller está el botón Papeles de taller, arriba de la lista de aberturas. Genera tres PDF:\n- Corte, con el diagrama de cada barra a escala y el corte del vidrio sobre la plancha.\n- Materiales, con perfiles, vidrios y accesorios separados por rubro.\n- Etiquetas, con un rótulo por pieza para pegar sobre el material cortado.\n\nLas barras se optimizan con todas las aberturas del presupuesto juntas, y así se compran menos barras. Los largos salen de las fórmulas cargadas. Antes de cortar, verificalos contra la tabla del fabricante de tu línea.','\n',char(10)),'["https://netunlock.github.io/cotizador-aberturas/img/foro/diagrama_corte.jpg"]','2026-09-14 12:02:38',0);
INSERT INTO "respuestas" ("id","usuario_id","id_pregunta","contenido","imagenes","fecha","votos") VALUES(23,8,21,replace('No hay una pantalla de descuentos aparte. El descuento es el número que va dentro de la fórmula de corte de cada perfil, porque cada perfil tiene el suyo. En la tabla de Aluar para Módena, por ejemplo, el umbral 6200 se carga como A - 42 y el parante de hoja 6203 como H - 79. Ese 42 y ese 79 son los descuentos.\n\nEl orden de carga importa:\n1. En Materiales y Costos, pestaña Líneas y precios, creá la línea si todavía no existe.\n2. En la pestaña Perfiles, elegí la línea arriba y cargá cada perfil con su código y su peso en kg por metro.\n3. En Fórmulas de despiece, elegí la tipología y la línea. Agregá un renglón por pieza con su fórmula y su cantidad.\n4. Tocá Probar despiece con una medida conocida y compará el resultado con la tabla del fabricante.\n\nSi un perfil no está cargado en Perfiles, no aparece para elegirlo en las fórmulas. El programa ya trae las líneas Clásica y Actual de MDT con sus medidas de corte. Módena y cualquier otra línea se cargan a mano o importando el catálogo desde Excel.','\n',char(10)),NULL,'2026-09-14 12:02:39',0);
CREATE TABLE votos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  usuario_id INTEGER NOT NULL,
  tipo TEXT NOT NULL,
  contenido_id INTEGER NOT NULL,
  tipo_voto TEXT NOT NULL,
  UNIQUE(usuario_id, tipo, contenido_id),
  FOREIGN KEY(usuario_id) REFERENCES usuarios(id)
);
INSERT INTO "votos" ("id","usuario_id","tipo","contenido_id","tipo_voto") VALUES(7,7,'respuestas',2,'up');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('usuarios',9);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('preguntas',21);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('respuestas',23);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('votos',7);
